apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: default
spec:
  type: state.store
  version: v1
  metadata:
    - name: redisHost
      value: redis:6379
    - name: redisPassword
      value: ""
    - name: initTimeout
      value: 5m
    - name: timeout
      value: 100s
