name: conformance-test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: setup go
        uses: actions/setup-go@v3
        with:
          go-version: ">=1.19.0"

      - name: Check out code
        uses: actions/checkout@v3
      - name: Run Redis docker
        shell: bash
        run: docker run -d -it -p 6379:6379 redislabs/redisearch:latest

      - name: Run Redis component
        shell: bash
        run: |
          DAPR_COMPONENT_SOCKET_PATH=/tmp/socket.sock go run examples/redis/main.go &
          until [ -S /tmp/socket.sock ]
          do
              sleep 5
              echo "waiting until component is ready"
          done

      - name: Conformance Tests
        uses: mcandeia/action-dapr-conformance-tests@v1
        with:
          socket: /tmp/socket.sock
          metadata: |
            redisHost: "localhost:6379"
            redisPassword: ""
            initTimeout: "5m"
            timeout: "100s"
          operations: |
            - get
